name: PR Welcome Message

on:
  workflow_call:

jobs:
  welcome_message:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(JSON.stringify(context))
            # await github.issues.createComment({
            #   issue_number: issueNumber,
            #   owner,
            #   repo,
            #   body: 'Testing',
            # })
