name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  title_check:
    uses: bluescape/reusable-github-workflows/.github/workflows/validate_pr.yml@dev/lmartin/test-2