name: Validate PR

on:
  workflow_call:
    inputs:
      title:
        description: Title
        required: false
        type: string
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  title_check:
    name: Title Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && ! contains( github.event.pull_request.labels.*.name, 'SKIP PR VALIDATION')
    steps:
      - name: Verify that the PR title starts with a JIRA
        env:
          PR_TITLE: ${{ inputs.title || github.event.pull_request.title }}
        run: |
          if (!/^(Revert \")*[a-zA-Z0-9]{2,10}(?<![J-j][I-i][R-r][A-a])-[0-9]{1,10}( |:|-|,).+/.test(process.env.PR_TITLE)) {
            console.error('PR Title does not match regex pattern!\nPlease follow format: "<JIRA_PROJ>-<JIRA_NUM>: <TITLE>"\nExample: "JIRA-404: Title Here"');
            process.exit(1);
          } else {
            console.log('Title passed validation!')
          }
        shell: node {0}
