name: Validate PR

on:
  workflow_call:

jobs:
  title_check:
    name: Title Validation
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR Title Contains a JIRA
        if: ${{ ! contains( github.event.pull_request.labels.*.name, 'SKIP PR VALIDATION') }}
        run: echo "${{ github.event.pull_request.title }}" | grep -Pq '^[a-zA-Z]{2,10}-[0-9]{1,10}( |:|-|,).+'
