name: Validate PR

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  title_check:
    name: Title Validation
    runs-on: ubuntu-latest
    steps:
      - name: Verify that the PR title starts with a JIRA
        if: ${{ ! contains( github.event.pull_request.labels.*.name, 'SKIP PR VALIDATION') }}
        run: |
          PR_TITLE=${{ 'github.event.pull_request.title'//\'\"/ }}
          echo $PR_TITLE | grep -Pq '^(Revert )*[a-zA-Z0-9]{2,10}-[0-9]{1,10}( |:|-|,).+'
